# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Stanley Katende 
repository: skatende-technieknowhow/portfolio
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to SK web Developer projects portfolio website where you will find a list of
  projects that I have worked on, and the projects which are work on progress.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "https://skatende-technieknowhow.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
# theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin : "contrast"  #"default" # "dark" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# Reading files
include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Pages Front Matter defaults can be scoped like this:
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# adding images in the header
header:
  # image:  /assets/images/universe.png

# Site Author
footer:
  links:
    - label:  "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/skatende-TechnieKnowHow"
    - label:  "Linkdin"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/stanley-katende/"


# Disable Feed Icons
atom_feed:
  hide: true